### ISSUE TITLE
Finetune Phase Faild

### ISSUE THREAD

**Issue by Yefancy** [kingdomrush2/CrossHAR#3]
When I was trying to execute the example code I got an error with cmd
```shell
python classifier.py -d uci -lr 0.1
```
and console log
```shell
Traceback (most recent call last):
  File "/workspace/classifier.py", line 55, in <module>
    classify_embeddings(args, embedding, labels, args.label_index, training_rate, label_rate, balance=balance, method=method)
  File "/workspace/classifier.py", line 18, in classify_embeddings
    , label_rate=label_rate, merge=model_cfg.seq_len, seed=train_cfg.seed
AttributeError: 'ClassifierModelConfig' object has no attribute 'seq_len'
```

<img width="878" alt="image" src="https://github.com/user-attachments/assets/116573f9-6ae2-4e7c-b2c5-57a9a0476524">

There is no seq_len in the ClassifierModelConfig. Therefore, I added `seq_len: int = 120` for it.

Unfortunately, I got a new error:

```shell
Traceback (most recent call last):
  File "/workspace/classifier.py", line 55, in <module>
    classify_embeddings(args, embedding, labels, args.label_index, training_rate, label_rate, balance=balance, method=method)
  File "/workspace/classifier.py", line 40, in classify_embeddings
    trainer.train(data_loader_train, data_loader_vali, data_loader_test, len(data_test))
  File "/workspace/finetune_train.py", line 34, in train
    loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.

Process finished with exit code 1
```

labels do not match number. 

could you please refine your code, Im really looking forward to it

**Comment by kingdomlys** [comment]
merge=dataset_cfg.seq_len
